/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import {ContractArtifact} from 'ethereum-types';

import * as Verifier from '../generated-artifacts/Verifier.json';
export const artifacts = {Verifier: Verifier as ContractArtifact};
