/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import {ContractArtifact} from 'ethereum-types';

import * as LibLimb from '../generated-artifacts/LibLimb.json';
import * as Verifier from '../generated-artifacts/Verifier.json';
export const artifacts = {
    LibLimb: LibLimb as ContractArtifact,
    Verifier: Verifier as ContractArtifact,
};
